### PR TITLE
Simplify deregister_pid function

### PR DESCRIPTION
**Pull request by milmazz**
IMHO, this approach demonstrate our real intention, which is to keep all those pids that are different from the input. wdyt?

### CODE REVIEW

**Comment by sasa1977** [comment]
Thanks for pointing this out!

Your code is definitely more concise and easier to understand. Another way would be to use a comprehension. Here's an untested sketch:

```elixir
for {_registered_alias, registered_process} = entry <- process_registry, 
    registered_process != pid,
    into: %{},
    do: entry
```

However, the real intention is in fact what I wrote in the comment, namely to only delete needless entries. The reason I chose this approach is performance.

A problem with your code (and the `for` version above) is that most of the map is rebuilt from scratch. We're removing one process, and I'd expect (based on how I normally use a registry) that most registered processes have one or maybe two aliases. If we have many registered processes, we'll end up recreating a possibly large map, when we only need to delete one or just a few entries.

So deletion here is deliberately chosen, though thanks to your comment I understand I should give an explanation why is this so :-). 

So instead of proposed changes I think it would be better to expand the comment. We could include your code sample in the comment and explain that this is more readable, but it's not chosen because it might not perform well in the general case with many registered processes.

What do you think?

**Comment by sasa1977** [comment]
Thinking some more about this, perhaps it actually makes more sense to use a simpler code, such as the one you posted.

This registry is just a simple placeholder anyway, and as I explain in the book, we'll ultimately replace it with the [gproc](https://github.com/uwiger/gproc) library. Thus, performance doesn't matter in this particular case so it makes sense to use a simpler version to avoid confusing people needlessly.

I'll take a couple of days to think about it, and then I'll either merge your pull, or comment the reasoning behind the more complicated code.

If you have some thoughts on this dilemma, I'll be happy to read them :-)

**Comment by milmazz** [comment]
Your example using comprehension is also very clear and succinct, but is, even more, slow than my approach, as you already pointed out is because we built a Map from scratch in both cases.

To me is clear that your original approach is more performant than mine, but following the listings (chapter 9) of the book we know that the pool size is just 3 workers, that is why I think is safe to assume that performance is not so critical at this point.

You also mention that we're doing manually the process registry for now (but it's not the right way to do things), then in chapter 10 you introduce concepts like ETS where we replace the process registry mechanism, and then finally we use gproc. So, this original function at the end does not exist anymore :)

**Comment by sasa1977** [comment]
I'd actually expect a comprehension to be somewhat faster, at least for large collections, since we don't build an intermediate list of tuples. But this is just a guess, without any measurements :-)

In any case, I tend to agree with you that simpler approach works better here, so I'll probably merge your pull, but I'll take a day or two to think about it.

Thanks again for pointing this out, and hope you enjoyed the book :-)

**Comment by milmazz** [comment]
> I'd actually expect a comprehension to be somewhat faster, at least for large collections, since we don't build an intermediate list of tuples. But this is just a guess, without any measurements :-)

This is the result after a quick test on Windows and OS X with Benchfella:

```console
mix bench
Settings:
  duration:      1.0 s

## Demo.RegisterBench
[20:33:19] 1/3: deregister_pid_with_for
[20:33:21] 2/3: deregister_pid_with_filter
[20:33:23] 3/3: deregister_pid

Finished in 5.29 seconds

## Demo.RegisterBench
deregister_pid                      10   117878.20 µs/op
deregister_pid_with_filter           5   299213.40 µs/op
deregister_pid_with_for              2   566567.50 µs/op
```

This is the code that I used, please let me know if you see something weird.

```elixir
defmodule Demo.RegisterBench do

  use Benchfella

  @process_registry Enum.into(1..1_000_000, %{}, fn(x) -> {x, x} end)
  @target 500_000

  def deregister_pid(process_registry, pid) do
    Enum.reduce(
      process_registry,
      process_registry,
      fn
        ({registered_alias, registered_process}, registry_acc) when registered_process == pid ->
          Map.delete(registry_acc, registered_alias)

        (_, registry_acc) -> registry_acc
      end
    )
  end

  def deregister_pid_with_filter(process_registry, pid) do
    process_registry
    |> Enum.filter(fn({_registered_alias, registered_process}) -> registered_process != pid end)
    |> Enum.into(%{})
  end

  def deregister_pid_with_for(process_registry, pid) do
    for {_registered_alias, registered_process} = entry <- process_registry,
        registered_process != pid,
        into: %{},
        do: entry
  end

  bench "deregister_pid", do: deregister_pid(@process_registry, @target)

  bench "deregister_pid_with_filter", do: deregister_pid_with_filter(@process_registry, @target)

  bench "deregister_pid_with_for", do: deregister_pid_with_for(@process_registry, @target)
end
```

> In any case, I tend to agree with you that simpler approach works better here, so I'll probably merge your pull, but I'll take a day or two to think about it.

No problem, take your time on your decision, and thanks for considering this, I just want to help :-)

> Thanks again for pointing this out, and hope you enjoyed the book :-)

Thanks to you for your hard work, I really enjoy and learn new things from the part 2 and 3 of the book, it's great to see how the TODO project evolves almost from the scratch and then see how we can get rid of source code and simple begin to stand on the shoulder of giants in part 3 (plug, gproc, etc.).

**Comment by sasa1977** [comment]
Well, that's unexpected, but I guess it proves it's better to bench than take wild guesses :-)

Looking at the code, I can see that `Enum.into` will use [map functions directly when merging a list into a map](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/enum.ex#L980-L982). Looking into Erlang source, I can see that [the functions used are BIFs](https://github.com/erlang/otp/blob/maint/lib/stdlib/src/maps.erl#L29-L30), i.e. powered by the C code. 

I guess this is where the perf gain might happen, because incremental building with `for` adds one by one element from the Erlang code, while with `Enum.into` we end up calling the C code to merge everything in a single pass.

This is still just a guess that should be proved by profiling, but this is the current explanation I have, simply by taking a glance at the sources :-)

**Comment by sasa1977** [comment]
Thanks again for pointing this out :-)

**Pull request merged**
